#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing'

#check pretiier
npm run check-format ||
(
    echo 'Prettier Check failed. Run npm run format, add changes and try coomit again';
    false;
)

#Check tsconfig 
npm run check-types ||
(
    echo 'Failed Type check . Make the changes require above, add changes and try to commit again';
    false;
)
npm run build ||
(
    echo 'Your build failed, view the errors above';
    false;
)

echo 'Succes Commite'